### ISSUE TITLE
Enable optee-examples in dk2

### ISSUE THREAD

**Issue by neithanmo** [Zondax/buildroot-zondax#1]
There is an issue with the optee-examples package that causes a compilation error.

**Comment by neithanmo** [comment]
The current error is due to a mismatch examples version. dk2 board supports only **optee-os 3.12** , for this reason, we have to downgrade the buildroot version we are currently using or find a mechanism to tell buildroot to use our custom version. the latter would be the ideal solution as we have to support different platforms which could have different requirements on the optee version they support.

**Comment by jleni** [comment]
In DK2 the problem is that OPTEE is not activated at boot time.
Additional info in available in our internal coda

**Comment by neithanmo** [comment]
closed by #11 which also integrates the optee xtests package which is even more important to have than optee-examples.
