### ISSUE TITLE
Enable offline signing of TAs

### ISSUE THREAD

**Issue by neithanmo** [Zondax/buildroot-zondax#15]
By passing  `TA_SIGN_KEY="path_to_our_pubkey_.pem"` to optee-os, using **buildroot**, like:

`BR2_TARGET_OPTEE_OS_ADDITIONAL_VARIABLES="TA_SIGN_KEY=my_key.pem"`

we can tell optee-os the key it must use to verify signed TAs. This also requires some extra steps as described [here](https://optee.readthedocs.io/en/latest/building/trusted_applications.html#offline-signing-of-tas) that should be included into our build steps.

It seems that there could be other issues when the **TA_SIGN_KEY** envar is set, according to this [issue](https://github.com/OP-TEE/optee_os/issues/4038).

We should evaluate this using qemu at least and integrate it in the other targets.

**Comment by neithanmo** [comment]
It seems that the issue was fixed and the offline signing documentation was updated and it is really clear now on how to proceed for signing TAs.

**Comment by jleni** [comment]
@neithanmo can we close this because of #23 #22 ?

**Comment by neithanmo** [comment]
yes, we can.. tested on both boards, imx and dk2
