### ISSUE TITLE
[imx8] Verify uboot and bootloader authentication

### ISSUE THREAD

**Issue by neithanmo** [Zondax/buildroot-zondax#3]
The bootloader and uboot should be validated before booting the image, for this keys and certificates are used.

**Comment by neithanmo** [comment]
https://github.com/bootlin/buildroot-external-st/commit/995f110d501636faece3697df57a91875308eda1

**Comment by neithanmo** [comment]
for the dk2 build, this has been already implemented and tested in a close board,
in theory it is ready to be tested on imx board, the missing part is to fuse keys on imx and check that it boots a signed image.
for dk2 see #29 and #32 and for imx see #32

**Comment by carlosala** [comment]
Should I test it in my `dk2` board? What is missing here?

**Comment by carlosala** [comment]
Tested and working properly in `dk2`. Closing!
