### ISSUE TITLE
Add the hello-rustee package

### ISSUE THREAD

**Issue by neithanmo** [Zondax/buildroot-zondax#4]
The simple [hello-rustee](https://github.com/Zondax/hello-rustee) application should be installed on the final image.

**Comment by neithanmo** [comment]
helpful [link](https://buildroot.org/downloads/manual/manual.html#_integration_of_cargo_based_packages)

**Comment by jleni** [comment]
I have included an initial example, however there are some points missing:

- [x] we need a special branch for hello-rustee + framework and clean them up so we simplify the build process and adapt it to buildroot
- [x] at the moment, it is deactivated. It needs to be fixed and activated again.

The easiest way to test this is:
a. use qemu `make zondaxtee_qemu_defconfig` and then `make`
b. build the deactivated component `make hellorustee`

**Comment by neithanmo** [comment]
We can not close this issue yet. Although #14 implements the require infrastructure, we need to port it for the other boards:

- [x] qemu is done
- [ ] stm32mp157
- [ ] imx8mm-evk

this would be mostly an update to the hash in the rust-bin-nightly package, and enable the packages in their config.in file
