### ISSUE TITLE
Automatically patch host-qemu

### ISSUE THREAD

**Issue by neithanmo** [Zondax/buildroot-zondax#6]
There is an [issue](https://stackoverflow.com/questions/70442995/buildroot-passing-host-cflags) when trying to build and run qemu

**Comment by jleni** [comment]
I found a way to fix the problem but we would need to integrate this as a buildroot automatic patch.

The current fix is to replace line 11 in 

`buildroot-zondax/buildroot/output/build/host-qemu-6.1.0/pc-bios/optionrom/Makefile`

and add `-fcf-protection=none` 

this results in 

```
CFLAGS = -O2 -g -fcf-protection=none
```

after this... everything compiles correctly
